-- NLE nursing question bank. Public read so the quiz PWA can load items.
-- Writes are reserved for SQL editor / service role (no anon insert).

create table if not exists public.questions (
  id bigint generated always as identity primary key,
  source_id integer not null unique,
  stem text not null,
  choices text[] not null,
  answer smallint not null check (answer >= 0 and answer <= 3),
  explanation text not null,
  rationales text[] not null,
  component text not null,
  topic text not null,
  topic_group text not null,
  subtopic text,
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
  bloom text,
  competency text,
  source text,
  source_version text,
  source_verification_level text,
  reviewer_status text,
  last_verified date,
  date_added date,
  created_at timestamptz not null default now()
);

create index if not exists questions_component_topic_idx
  on public.questions (component, topic_group, difficulty);

alter table public.questions enable row level security;

grant select on table public.questions to anon, authenticated;

drop policy if exists "public can read questions" on public.questions;
create policy "public can read questions"
on public.questions
for select
to anon, authenticated
using (true);
insert into public.questions (
  source_id, stem, choices, answer, explanation, rationales,
  component, topic, topic_group, subtopic, difficulty, bloom,
  competency, source, source_version, source_verification_level,
  reviewer_status, last_verified, date_added
) values
  (1, $$Nurse Santos is teaching a client newly diagnosed with pulmonary tuberculosis about the DOTS regimen before discharge. Which statement by the client indicates a need for further teaching?$$, ARRAY[$$I should cover my mouth when I cough until my doctor says I'm no longer contagious.$$, $$I can stop my medicines once my cough goes away.$$, $$I need a treatment partner to watch me take my medicine every dose.$$, $$I need to return for sputum exams to check my progress.$$]::text[], 1, $$Needs correction — DOTS requires completing the full prescribed course (about 6 months for the standard regimen) even after symptoms resolve; stopping early risks relapse and multidrug-resistant TB.$$, ARRAY[$$Correct infection-control practice; covering the mouth while coughing reduces droplet spread until the client is confirmed noninfectious, so this statement does not need correction.$$, $$Needs correction — DOTS requires completing the full prescribed course (about 6 months for the standard regimen) even after symptoms resolve; stopping early risks relapse and multidrug-resistant TB.$$, $$Correct understanding — a treatment partner (health worker or trained community supporter) observing each dose is the core of the DOTS strategy per the NTP Manual of Procedures.$$, $$Correct understanding — follow-up sputum smear microscopy monitors treatment response and confirms conversion to noninfectious status.$$]::text[], $$Nursing Practice I$$, $$Communicable Disease Control - Tuberculosis - DOTS$$, $$Communicable Disease Control$$, $$Tuberculosis - DOTS$$, $$medium$$, $$Application$$, $$Health Education$$, $$DOH National TB Control Program - NTP Manual of Procedures, 6th Edition$$, $$6th Edition (current)$$, $$Secondary/summary source$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (2, $$Nurse Cruz is assigned to four clients at the start of the shift. Which client should be assessed first?$$, ARRAY[$$A newly admitted client with active pulmonary tuberculosis not yet placed on isolation$$, $$A client due for a scheduled dressing change$$, $$A client with a 3-day-old surgical wound requesting pain medication$$, $$A client asking for discharge instructions$$]::text[], 0, $$Correct — an unisolated client with active, airborne-transmissible TB poses an immediate exposure risk to other clients and staff and must be assessed and placed on airborne precautions first.$$, ARRAY[$$Correct — an unisolated client with active, airborne-transmissible TB poses an immediate exposure risk to other clients and staff and must be assessed and placed on airborne precautions first.$$, $$A routine, scheduled task without acute risk; can be done after the priority safety issue is addressed.$$, $$Pain is important but not immediately life- or safety-threatening compared to an active airborne infection risk to the unit.$$, $$A non-urgent informational need that can wait until safety priorities are addressed.$$]::text[], $$Nursing Practice I$$, $$Communicable Disease Control - Tuberculosis - Infection Control/Prioritization$$, $$Communicable Disease Control$$, $$Tuberculosis - Infection Control/Prioritization$$, $$medium$$, $$Analysis$$, $$Safe Quality Care$$, $$DOH National TB Control Program; CDC TB Infection Control$$, $$Current guidance (2026)$$, $$Secondary/summary source$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (3, $$During a home visit, Nurse Bautista assesses a 7-year-old with dengue fever: temperature 38.9°C, delayed capillary refill, and cold, clammy extremities. What is the priority action?$$, ARRAY[$$Give paracetamol and recheck temperature in 4 hours$$, $$Encourage oral fluids and monitor at home$$, $$Advise rest and follow up tomorrow$$, $$Refer immediately for emergency care$$]::text[], 3, $$Correct — per the WHO 2009 dengue classification, cold/clammy extremities and delayed capillary refill (>2 sec) are signs of compensated shock (Dengue Shock Syndrome/Severe Dengue), distinct from and more advanced than the 'warning signs' category (e.g., persistent vomiting, abdominal pain, mucosal bleeding). This requires immediate emergency management.$$, ARRAY[$$Treats the fever but ignores cold, clammy extremities and delayed capillary refill, which are diagnostic criteria for compensated shock (Severe Dengue), not just early warning signs — this delay could be dangerous.$$, $$Appropriate for dengue without warning signs, but this child already meets criteria for compensated shock (narrowed perfusion), which needs urgent evaluation, not home monitoring.$$, $$Delaying care risks progression from compensated to decompensated (hypotensive) shock, which can deteriorate rapidly.$$, $$Correct — per the WHO 2009 dengue classification, cold/clammy extremities and delayed capillary refill (>2 sec) are signs of compensated shock (Dengue Shock Syndrome/Severe Dengue), distinct from and more advanced than the 'warning signs' category (e.g., persistent vomiting, abdominal pain, mucosal bleeding). This requires immediate emergency management.$$]::text[], $$Nursing Practice I$$, $$Communicable Disease Control - Dengue - Warning Signs/Shock$$, $$Communicable Disease Control$$, $$Dengue - Warning Signs/Shock$$, $$hard$$, $$Analysis$$, $$Safe Quality Care$$, $$WHO 2009 Dengue Guidelines (severity classification); DOH Dengue Prevention and Control Program$$, $$WHO 2009 classification (current)$$, $$Primary source confirmed$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (4, $$During a barangay health station screening, a 50-year-old man with no prior diagnosis of hypertension has a BP of 158/96 mmHg, taken correctly with an appropriately sized cuff. He has no symptoms. What is the most appropriate nursing action?$$, ARRAY[$$Diagnose the client with hypertension and start antihypertensive therapy$$, $$Document the finding and schedule a repeat BP measurement on a separate day before referral$$, $$Reassure the client that a single elevated reading is not clinically significant$$, $$Refer immediately to the hospital emergency department$$]::text[], 1, $$Correct — opportunistic screening protocols call for confirming an elevated reading on a separate occasion before diagnosis, then referring for further evaluation if it remains elevated.$$, ARRAY[$$PhilPEN's task-shifting model does allow trained non-physician health workers to initiate protocol-based antihypertensive management at the primary care level in some cases, so 'outside the nurse's scope' may overstate the restriction — the real issue is whether this specific reading meets the protocol's threshold for same-visit treatment vs. confirmation first. NEEDS SME VERIFICATION against the actual PhilPEN algorithm.$$, $$Correct — opportunistic screening protocols call for confirming an elevated reading on a separate occasion before diagnosis, then referring for further evaluation if it remains elevated.$$, $$A BP of 158/96 mmHg is in the Stage 2 hypertension range and should not be dismissed as insignificant, even without symptoms.$$, $$Emergency referral is reserved for hypertensive urgency/emergency (severely elevated BP with symptoms of end-organ damage), which this client does not show.$$]::text[], $$Nursing Practice I$$, $$Non-Communicable Disease Prevention - Hypertension - Screening Protocol$$, $$Non-Communicable Disease Prevention$$, $$Hypertension - Screening Protocol$$, $$medium$$, $$Application$$, $$Safe Quality Care$$, $$DOH PhilPEN Program$$, $$Current guidance (2026)$$, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (5, $$Nurse Aquino conducts a diabetes prevention class for adults with risk factors. Which statement by a participant needs correction?$$, ARRAY[$$Being overweight increases my risk for type 2 diabetes.$$, $$Regular exercise can help lower my risk.$$, $$Since diabetes runs in my family, there's nothing I can do to prevent it.$$, $$Eating more vegetables and less sugary food can help.$$]::text[], 2, $$Needs correction — genetic predisposition raises risk but does not eliminate the benefit of lifestyle modification; primary prevention can still meaningfully lower risk.$$, ARRAY[$$Correct understanding — obesity is a well-established modifiable risk factor for type 2 diabetes.$$, $$Correct understanding — regular physical activity improves insulin sensitivity and lowers risk.$$, $$Needs correction — genetic predisposition raises risk but does not eliminate the benefit of lifestyle modification; primary prevention can still meaningfully lower risk.$$, $$Correct understanding — dietary modification is a core component of primary prevention.$$]::text[], $$Nursing Practice I$$, $$Non-Communicable Disease Prevention - Diabetes - Primary Prevention$$, $$Non-Communicable Disease Prevention$$, $$Diabetes - Primary Prevention$$, $$easy$$, $$Recall/Comprehension$$, $$Health Education$$, $$DOH PhilPEN Program; CDC Diabetes Prevention$$, $$Current guidance (2026)$$, $$Secondary/summary source$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (6, $$Nurse Ramos has four home visits scheduled today. Which family should be prioritized?$$, ARRAY[$$A family with a member newly diagnosed with pulmonary tuberculosis$$, $$A family with a newborn due for a well-baby check next month$$, $$A family whose child completed all immunizations$$, $$A family requesting a certificate of residency$$]::text[], 0, $$Correct — a newly diagnosed communicable disease case carries transmission risk to the household and requires prompt case management and contact assessment.$$, ARRAY[$$Correct — a newly diagnosed communicable disease case carries transmission risk to the household and requires prompt case management and contact assessment.$$, $$A scheduled preventive visit that is not yet due; lower urgency than an active communicable disease case.$$, $$No pending health need identified; lowest urgency of the four.$$, $$An administrative request unrelated to an acute health need.$$]::text[], $$Nursing Practice I$$, $$Family Health Nursing - Home Visit Prioritization$$, $$Family Health Nursing$$, $$Home Visit Prioritization$$, $$medium$$, $$Analysis$$, $$Safe Quality Care$$, $$Original (family health nursing prioritization)$$, NULL, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (7, $$During a home visit, Nurse Dela Cruz notes an unemployed father, a mother in her third trimester with no prenatal checkups, and a child with no vaccinations. What should the nurse do first?$$, ARRAY[$$Refer the family to social services immediately$$, $$Schedule the child's immunizations today$$, $$Report the family to the barangay captain$$, $$Conduct a comprehensive family health assessment$$]::text[], 3, $$Correct — the nursing process begins with a comprehensive assessment to identify all needs and resources before planning or referring.$$, ARRAY[$$Referral may ultimately be appropriate but should follow a full assessment of the family's needs and resources, not precede it.$$, $$Addresses one need in isolation without first understanding the family's overall situation and priorities.$$, $$Not an appropriate first response; this is a health and social need, not a matter requiring barangay reporting.$$, $$Correct — the nursing process begins with a comprehensive assessment to identify all needs and resources before planning or referring.$$]::text[], $$Nursing Practice I$$, $$Family Health Nursing - At-Risk Families - Nursing Process$$, $$Family Health Nursing$$, $$At-Risk Families - Nursing Process$$, $$medium$$, $$Application$$, $$Safe Quality Care$$, $$Original (family nursing process framework)$$, NULL, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (8, $$Two days after a typhoon, Nurse Flores assesses an evacuation center of 300 individuals. She notes one functioning water source, several children with loose stools, and no handwashing stations. Which action should be implemented first?$$, ARRAY[$$Set up handwashing and safe water stations at the center$$, $$Conduct active case finding for additional diarrhea cases among residents$$, $$Distribute oral rehydration salts to symptomatic children$$, $$Organize a mobile clinic for chronic disease follow-up$$]::text[], 2, $$Correct — per the actual-before-potential prioritization principle, the immediate physiologic need of children already showing signs of illness (risk for dehydration) takes priority over measures aimed at preventing additional/future cases.$$, ARRAY[$$An essential outbreak-prevention measure, but it addresses future/potential cases rather than the actual, existing problem in the children already symptomatic.$$, $$Important for understanding outbreak scope, but it does not address the immediate physiologic risk (dehydration) facing children already symptomatic.$$, $$Correct — per the actual-before-potential prioritization principle, the immediate physiologic need of children already showing signs of illness (risk for dehydration) takes priority over measures aimed at preventing additional/future cases.$$, $$Chronic disease follow-up is not the priority in the acute post-disaster period, especially with an active diarrheal illness risk present.$$]::text[], $$Nursing Practice I$$, $$Community Health - Disaster Nursing - Outbreak Response Prioritization$$, $$Community Health - Disaster Nursing$$, $$Outbreak Response Prioritization$$, $$hard$$, $$Analysis$$, $$Safe Quality Care$$, $$Original (disaster nursing framework; actual-vs-potential prioritization principle)$$, NULL, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (9, $$A community health nurse discovers that a colleague has been recording immunizations that were never actually administered to several children. What is the most appropriate initial action?$$, ARRAY[$$Report the findings directly to the Professional Regulation Commission$$, $$Discuss the concern privately with the colleague, then escalate through the nursing supervisor if unresolved$$, $$Immediately administer the missed immunizations without informing anyone$$, $$Wait until the annual performance review to raise the concern$$]::text[], 1, $$Reflects a common professional-conduct convention (address directly, then escalate through channels), but we could not confirm this is the specific mandated sequence under RA 9173/PRC Board of Nursing rules for a case involving falsified client records. NEEDS SME/LEGAL VERIFICATION before this is treated as the definitive correct answer — falsified immunization records may warrant more immediate/direct reporting given the patient-safety and documentation-integrity stakes.$$, ARRAY[$$May eventually be necessary if internal channels fail, but going directly to an external regulatory body without first attempting internal resolution skips the appropriate chain of accountability.$$, $$Reflects a common professional-conduct convention (address directly, then escalate through channels), but we could not confirm this is the specific mandated sequence under RA 9173/PRC Board of Nursing rules for a case involving falsified client records. NEEDS SME/LEGAL VERIFICATION before this is treated as the definitive correct answer — falsified immunization records may warrant more immediate/direct reporting given the patient-safety and documentation-integrity stakes.$$, $$Fails to address the underlying falsified documentation or the risk to other children whose records may be affected; the issue must be formally addressed, not quietly corrected.$$, $$Unsafe and unethical practices affecting client welfare should be addressed promptly, not deferred to a routine administrative cycle.$$]::text[], $$Nursing Practice I$$, $$Ethico-Moral Responsibility / Legal - Professional Accountability/Reporting$$, $$Ethico-Moral Responsibility / Legal$$, $$Professional Accountability/Reporting$$, $$medium$$, $$Application$$, $$Ethico-Moral Responsibility / Legal$$, $$PRC Board of Nursing Resolution No. 220, s. 2004 (Code of Ethics for Registered Nurses)$$, $$2004 (current)$$, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (10, $$Nurse Reyes is asked by a local official why civil registration data matter for computing the maternal mortality ratio. What should the nurse explain?$$, ARRAY[$$They provide the record of births and maternal deaths used in the computation$$, $$They are used only for national census planning$$, $$They are optional and rarely used by the PSA$$, $$They replace the need for hospital records entirely$$]::text[], 0, $$Correct — the PSA computes vital statistics such as MMR primarily from civil registration data on live births and deaths.$$, ARRAY[$$Correct — the PSA computes vital statistics such as MMR primarily from civil registration data on live births and deaths.$$, $$The national census is a separate, periodic data source; civil registration is an ongoing system distinct from census planning.$$, $$Civil registration data are a core, actively used input for PSA vital statistics, not an optional afterthought.$$, $$Civil registration complements, but does not replace, other data sources such as hospital and facility-based records.$$]::text[], $$Nursing Practice I$$, $$Community Health - Vital Statistics - Maternal Mortality Ratio / CRVS$$, $$Community Health - Vital Statistics$$, $$Maternal Mortality Ratio / CRVS$$, $$medium$$, $$Application$$, $$Record Management$$, $$Philippine Statistics Authority - Vital Statistics$$, $$2024 data cited$$, $$Primary source confirmed$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (11, $$Which nursing action best reflects primary prevention of non-communicable disease?$$, ARRAY[$$Managing complications of stroke$$, $$Screening for elevated blood glucose$$, $$Rehabilitating a client after amputation$$, $$Conducting smoking cessation programs$$]::text[], 3, $$Correct — smoking cessation addresses a risk factor before disease onset, the definition of primary prevention.$$, ARRAY[$$Managing existing complications is tertiary prevention, not primary.$$, $$Screening to detect disease early is secondary prevention.$$, $$Rehabilitation after a complication has already occurred is tertiary prevention.$$, $$Correct — smoking cessation addresses a risk factor before disease onset, the definition of primary prevention.$$]::text[], $$Nursing Practice I$$, $$Levels of Prevention - Primary Prevention - NCD$$, $$Levels of Prevention$$, $$Primary Prevention - NCD$$, $$medium$$, $$Application$$, $$Safe Quality Care$$, $$Original (levels of prevention framework)$$, NULL, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (12, $$A nurse teaches barangay health workers about proper nutrition. Which nursing role is demonstrated?$$, ARRAY[$$Direct care provider$$, $$Policy advocate$$, $$Health educator$$, $$Researcher$$]::text[], 2, $$Correct — teaching a structured topic to a group is a health education/teaching role.$$, ARRAY[$$Direct care involves hands-on clinical care to an individual client, not teaching a group.$$, $$Policy advocacy involves influencing laws or institutional decisions, not conducting training.$$, $$Correct — teaching a structured topic to a group is a health education/teaching role.$$, $$Research involves systematic investigation to generate new knowledge, not delivering existing content.$$]::text[], $$Nursing Practice I$$, $$Roles of the Community Health Nurse - Health Educator Role$$, $$Roles of the Community Health Nurse$$, $$Health Educator Role$$, $$easy$$, $$Recall/Comprehension$$, $$Health Education$$, $$Original (roles of the community health nurse)$$, NULL, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (13, $$A public health nurse presents local smoking-related morbidity data at a municipal council hearing to support a smoke-free ordinance. Which nursing role is being performed?$$, ARRAY[$$Policy advocate$$, $$Direct care provider$$, $$Health educator$$, $$Case manager$$]::text[], 0, $$Correct — presenting evidence to influence legislation is the nurse acting as a policy advocate.$$, ARRAY[$$Correct — presenting evidence to influence legislation is the nurse acting as a policy advocate.$$, $$No hands-on client care is involved in this scenario.$$, $$Health education targets teaching individuals or groups directly, not influencing legislative bodies.$$, $$Case management involves coordinating an individual client's care across services, not policy work.$$]::text[], $$Nursing Practice I$$, $$Roles of the Community Health Nurse - Policy Advocate Role$$, $$Roles of the Community Health Nurse$$, $$Policy Advocate Role$$, $$medium$$, $$Application$$, $$Legal$$, $$Original (roles of the community health nurse)$$, NULL, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (14, $$A barangay-wide walking program and healthy food fair primarily reflect which DOH NCD strategy?$$, ARRAY[$$Early case detection$$, $$Rehabilitation services$$, $$Disease surveillance$$, $$Risk factor modification$$]::text[], 3, $$Correct — programs targeting diet and physical activity address modifiable risk factors, the core of DOH's risk factor modification strategy under PhilPEN.$$, ARRAY[$$Early case detection involves screening to find existing but undiagnosed disease, not lifestyle promotion.$$, $$Rehabilitation addresses recovery after disease/complications have occurred.$$, $$Surveillance involves systematic monitoring of disease patterns, not community lifestyle activities.$$, $$Correct — programs targeting diet and physical activity address modifiable risk factors, the core of DOH's risk factor modification strategy under PhilPEN.$$]::text[], $$Nursing Practice I$$, $$DOH NCD Strategy - Risk Factor Modification$$, $$DOH NCD Strategy$$, $$Risk Factor Modification$$, $$medium$$, $$Application$$, $$Health Education$$, $$DOH PhilPEN Program / Health Programs directory$$, $$Current guidance (2026)$$, $$Secondary/summary source$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (15, $$A nurse tracks monthly hypertension case counts across barangays to detect emerging clusters. Which nursing role is being performed?$$, ARRAY[$$Direct care$$, $$Surveillance/research$$, $$Health teaching$$, $$Policy advocacy$$]::text[], 1, $$Correct — systematically tracking disease patterns across a population to detect clusters reflects a surveillance/research role.$$, ARRAY[$$No direct hands-on client care is involved in this data-tracking activity.$$, $$Correct — systematically tracking disease patterns across a population to detect clusters reflects a surveillance/research role.$$, $$No teaching activity is described in this scenario.$$, $$No legislative or policy-influencing action is described.$$]::text[], $$Nursing Practice I$$, $$Roles of the Community Health Nurse - Surveillance/Research Role$$, $$Roles of the Community Health Nurse$$, $$Surveillance/Research Role$$, $$medium$$, $$Application$$, $$Research$$, $$Original (roles of the community health nurse)$$, NULL, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (16, $$Teaching foot care to a client with diabetes and peripheral neuropathy, but no active ulcers, is an example of which level of prevention?$$, ARRAY[$$Primary prevention$$, $$Health promotion only$$, $$Tertiary prevention$$, $$Secondary prevention$$]::text[], 2, $$Correct under the classic Leavell & Clark three-level model (this bank's default framework) — since the client already has diabetes with neuropathy, teaching foot care to prevent complications like ulcers is tertiary prevention. NOTE: some PNLE review materials/frameworks classify this differently (e.g., as secondary prevention aimed at preventing complications of an already-diagnosed disease before disability occurs). Lock this to whichever framework your primary PNLE review source uses, and flag for SME confirmation.$$, ARRAY[$$Primary prevention occurs before disease onset; this client already has diabetes with a complication (neuropathy).$$, $$Health promotion alone does not capture the goal of preventing further disability from an existing disease process.$$, $$Correct under the classic Leavell & Clark three-level model (this bank's default framework) — since the client already has diabetes with neuropathy, teaching foot care to prevent complications like ulcers is tertiary prevention. NOTE: some PNLE review materials/frameworks classify this differently (e.g., as secondary prevention aimed at preventing complications of an already-diagnosed disease before disability occurs). Lock this to whichever framework your primary PNLE review source uses, and flag for SME confirmation.$$, $$Secondary prevention involves early detection of disease that is not yet diagnosed; this client's diabetes and neuropathy are already established.$$]::text[], $$Nursing Practice I$$, $$Levels of Prevention - Tertiary Prevention - Diabetes$$, $$Levels of Prevention$$, $$Tertiary Prevention - Diabetes$$, $$hard$$, $$Analysis$$, $$Safe Quality Care$$, $$Original (levels of prevention framework)$$, NULL, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (17, $$A nurse computes the number of existing dengue cases in a community at a specific point in time. What is being measured?$$, ARRAY[$$Prevalence$$, $$Incidence$$, $$Mortality rate$$, $$Attack rate$$]::text[], 0, $$Correct — prevalence measures all existing cases (new and pre-existing) at a specific point in time.$$, ARRAY[$$Correct — prevalence measures all existing cases (new and pre-existing) at a specific point in time.$$, $$Incidence measures only new cases occurring within a defined period, not existing cases at a point in time.$$, $$Mortality rate measures deaths from a condition within a population, not case counts.$$, $$Attack rate is a form of incidence typically used in outbreak investigations over a short, defined period.$$]::text[], $$Nursing Practice I$$, $$Epidemiology - Prevalence vs Incidence$$, $$Epidemiology$$, $$Prevalence vs Incidence$$, $$medium$$, $$Recall/Comprehension$$, $$Research$$, $$Original (epidemiology concepts)$$, NULL, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (18, $$A household consisting of parents, their children, and a grandparent is classified as what family type?$$, ARRAY[$$Nuclear family$$, $$Extended family$$, $$Blended family$$, $$Single-parent family$$]::text[], 1, $$Correct — a household spanning more than two generations under one roof is defined as an extended family.$$, ARRAY[$$A nuclear family consists only of parents and their children, without other relatives in the household.$$, $$Correct — a household spanning more than two generations under one roof is defined as an extended family.$$, $$A blended family results from remarriage combining children from previous relationships, which is not described here.$$, $$A single-parent family has only one parent present, which is not the case here.$$]::text[], $$Nursing Practice I$$, $$Family Health Nursing - Family Types/Classification$$, $$Family Health Nursing$$, $$Family Types/Classification$$, $$easy$$, $$Recall/Comprehension$$, $$Safe Quality Care$$, $$Original (family health nursing - family types)$$, NULL, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (19, $$Which method provides the most objective evaluation of a psychomotor skill taught during health teaching?$$, ARRAY[$$Verbal feedback from the learner$$, $$Written examination$$, $$Attendance record$$, $$Return demonstration$$]::text[], 3, $$Correct — return demonstration objectively confirms psychomotor skill acquisition by having the learner perform the skill directly.$$, ARRAY[$$Self-reported understanding does not confirm the learner can actually perform the skill.$$, $$A written test measures knowledge recall, not the ability to physically perform a skill.$$, $$Attendance shows presence, not learning or skill acquisition.$$, $$Correct — return demonstration objectively confirms psychomotor skill acquisition by having the learner perform the skill directly.$$]::text[], $$Nursing Practice I$$, $$Health Education - Evaluation of Learning$$, $$Health Education$$, $$Evaluation of Learning$$, $$easy$$, $$Analysis$$, $$Health Education$$, $$Original (health education/evaluation principles)$$, NULL, $$General knowledge - flagged for SME review$$, $$Pending RN Review$$, NULL, '2026-08-07'::date),
  (20, $$Empowering community members to identify and act on their own health needs reflects which principle of Primary Health Care?$$, ARRAY[$$Equitable distribution$$, $$Appropriate technology$$, $$Community participation$$, $$Intersectoral collaboration$$]::text[], 2, $$Correct — community participation empowers people to engage in decisions about their own health, a core PHC principle reaffirmed in the Declaration of Astana.$$, ARRAY[$$Equitable distribution refers to fair access to health resources and services, not community involvement in decision-making.$$, $$Appropriate technology refers to using cost-effective, acceptable methods suited to local resources, not community empowerment specifically.$$, $$Correct — community participation empowers people to engage in decisions about their own health, a core PHC principle reaffirmed in the Declaration of Astana.$$, $$Intersectoral collaboration refers to cooperation across sectors (health, education, agriculture, etc.), not community self-determination specifically.$$]::text[], $$Nursing Practice I$$, $$Community Health - Primary Health Care - PHC Principles - Community Participation$$, $$Community Health - Primary Health Care$$, $$PHC Principles - Community Participation$$, $$medium$$, $$Application$$, $$Safe Quality Care$$, $$WHO Declaration of Astana (2018)$$, $$2018 (reaffirmed, current)$$, $$Primary source confirmed$$, $$Pending RN Review$$, NULL, '2026-08-07'::date)
ON CONFLICT (source_id) DO UPDATE SET
  stem = excluded.stem,
  choices = excluded.choices,
  answer = excluded.answer,
  explanation = excluded.explanation,
  rationales = excluded.rationales,
  component = excluded.component,
  topic = excluded.topic,
  topic_group = excluded.topic_group,
  subtopic = excluded.subtopic,
  difficulty = excluded.difficulty,
  bloom = excluded.bloom,
  competency = excluded.competency,
  source = excluded.source,
  source_version = excluded.source_version,
  source_verification_level = excluded.source_verification_level,
  reviewer_status = excluded.reviewer_status,
  last_verified = excluded.last_verified,
  date_added = excluded.date_added;
